language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
notifications:
  email: false
before_install:
  - npm update -g npm
  - nvm --version
node_js:
  - "8"
before_script:
  - yarn install
script:
  - yarn test
  - yarn build
jobs:
  include:
    - stage: release
      node_js: lts/*
      after_success:
        - npm run test:coverage
        - npm run semantic-release
        - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
