language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
  - nvm --version
node_js:
  - '8'
before_script:
  - sudo npm prune
  - sudo npm install
script:
  - npm run test
  - npm run build
after_success:
  - npm run test:coverage
  - npm run travis-deploy-once "npm run semantic-release"
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
