language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
notifications:
  email: false
before_install:
  - npm update -g npm
  - nvm --version
node_js:
  - "8"
before_script:
  - yarn install
script:
  - yarn test
  - yarn build
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run test:coverage
          - npx semantic-release
          - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
